# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/sata/UnrealEngine

TARGETS = \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	Game-Android-DebugGame  \
	Game-Android-Development  \
	Game-Android-Shipping  \
	Game-Linux-DebugGame  \
	Game-Linux-Development  \
	Game-Linux-Shipping  \
	Game-LinuxArm64-DebugGame  \
	Game-LinuxArm64-Development  \
	Game-LinuxArm64-Shipping  \
	Game \
	GameEditor-Linux-DebugGame  \
	GameEditor-Linux-Development  \
	GameEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend GameEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug GameEditor-Linux-Debug


ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

Game-Android-DebugGame:
	 $(BUILD) Game Android DebugGame  -Project="/mnt/sata/UnrealEngine/Projects/Game/Game.uproject" $(ARGS)

Game-Android-Development:
	 $(BUILD) Game Android Development  -Project="/mnt/sata/UnrealEngine/Projects/Game/Game.uproject" $(ARGS)

Game-Android-Shipping:
	 $(BUILD) Game Android Shipping  -Project="/mnt/sata/UnrealEngine/Projects/Game/Game.uproject" $(ARGS)

Game-Linux-DebugGame:
	 $(BUILD) Game Linux DebugGame  -Project="/mnt/sata/UnrealEngine/Projects/Game/Game.uproject" $(ARGS)

Game-Linux-Development:
	 $(BUILD) Game Linux Development  -Project="/mnt/sata/UnrealEngine/Projects/Game/Game.uproject" $(ARGS)

Game-Linux-Shipping:
	 $(BUILD) Game Linux Shipping  -Project="/mnt/sata/UnrealEngine/Projects/Game/Game.uproject" $(ARGS)

Game-LinuxArm64-DebugGame:
	 $(BUILD) Game LinuxArm64 DebugGame  -Project="/mnt/sata/UnrealEngine/Projects/Game/Game.uproject" $(ARGS)

Game-LinuxArm64-Development:
	 $(BUILD) Game LinuxArm64 Development  -Project="/mnt/sata/UnrealEngine/Projects/Game/Game.uproject" $(ARGS)

Game-LinuxArm64-Shipping:
	 $(BUILD) Game LinuxArm64 Shipping  -Project="/mnt/sata/UnrealEngine/Projects/Game/Game.uproject" $(ARGS)

Game: Game-Linux-Development

GameEditor-Linux-DebugGame:
	 $(BUILD) GameEditor Linux DebugGame  -Project="/mnt/sata/UnrealEngine/Projects/Game/Game.uproject" $(ARGS)

GameEditor-Linux-Development:
	 $(BUILD) GameEditor Linux Development  -Project="/mnt/sata/UnrealEngine/Projects/Game/Game.uproject" $(ARGS)

GameEditor: GameEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/mnt/sata/UnrealEngine/Projects/Game/Game.uproject" -Game 

.PHONY: $(TARGETS)
